---
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-symlinks
  - id: detect-private-key
