# Default values for meteor-pipelines.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
github-username: sesheta
github-token: "..."
github-webhook-secret: "..."
quay-dockerconfigjson: "{}"
pypi-username: sesheta
pypi-password: "..."
