---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: statusfy-thoth-station-ninja
  labels:
    app: aicoe-ci
spec:
  params:
    - name: git_ref
      type: string
    - name: repo_name
      type: string
  resources:
    - name: git-repo
      type: git
    - name: statusfy-thoth-station-ninja
      type: image

  tasks:
    - name: build
      taskRef:
        name: s2i-nodejs
      resources:
        inputs:
          - name: source
            resource: git-repo
        outputs:
          - name: image
            resource: statusfy-thoth-station-ninja
