apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: byon-validate-jupyterhub-image
spec:
  params:
    - name: url
      description: Container image repository url
      type: string
  workspaces:
    - name: data
  steps:
    - name: jupyter-book-build
      image: $(params.url)
      script: |
        #!/usr/bin/env bash
        # Check Python versionand
        echo  "Validating image:"

        # Check if Python was found, if not save that information to a message
        if command -v python >/dev/null; then
          version=$(python --version | cut -d ' ' -f 2)
          echo -n  "[{\"name\":\"Python\",\"version\":\"$version\"}]" > $(workspaces.data.path)/notebook-software.json
          echo  "    Python:     $version"
        else
           echo "    Python:     Not available"
           echo "{\"severity\":\"error\",\"message\":\"Python not found\"}" >> $(workspaces.data.path)/messages.ndjson
        fi

        # Check if Pip was found, if not save that information to a message
        if command -v pip >/dev/null; then
           echo -n $(pip list --disable-pip-version-check --not-required --format json) > $(workspaces.data.path)/notebook-python-dependencies.json
           echo -n  "    Packages:   "
           echo $(pip list --disable-pip-version-check --not-required --format=freeze)
        else
           echo "    Packages:   Not available"
           echo "{\"severity\":\"error\",\"message\":\"Pip not found\"}" >> $(workspaces.data.path)/messages.ndjson
        fi
