apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-jupyterbook
spec:
  workspaces:
    - name: data

  steps:
    - name: jupyter-book-build
      image: quay.io/thoth-station/s2i-jupyterbook:latest
      workingDir: $(workspaces.data.path)
      script: |
        start=`date +%s`
        jupyter-book build .
        end=`date +%s`
        mkdir -p .tekton_metrics
        echo "$((end-start))" > .tekton_metrics/content_build_duration

    - name: generate
      image: quay.io/openshift-pipeline/s2i:nightly
      workingDir: $(workspaces.data.path)
      command:
        - /usr/local/bin/s2i
        - --loglevel=0
        - build
        - ./_build/html
        - quay.io/centos7/httpd-24-centos7:latest
        - --as-dockerfile
        - ./Dockerfile
