apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: resolve-persistent-host
spec:
  params:
    - name: host
    - name: url
  results:
    - name: fullhost
  steps:
    - name: resolve-persistent-host
      image: quay.io/thoth-station/s2i-thoth-dev:latest
      env:
        - name: HOST
          value: $(params.host)
        - name: URL
          value: $(params.url)
        - name: RESULT
          value: $(results.fullhost.path)
      script: |
        #!/opt/app-root/bin/python
        import os
        with open(os.getenv("RESULT"), "w") as f:
            if not os.getenv("URL") or not os.getenv("HOST"):
                f.write("")
            else:
                f.write(os.getenv("URL").rsplit("/", 1)[-1] + "." + os.getenv("HOST"))
