apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: oc-actions
spec:
  params:
    - name: script
  results:
    - name: results
  workspaces:
    - name: data
      optional: true
  steps:
    - name: oc
      image: "image-registry.openshift-image-registry.svc:5000/openshift/cli:latest"
      script: |
        #!/usr/bin/env bash
        $(params.script)
