{{- define "imagePullSecret" }}
{{- with .Values.quay }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
    name: pypi-secret
data:
    password: {{ .Values.pypi.username | b64enc }}
    username: {{ .Values.pypi.password | b64enc }} 
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
    name: quay-pusher-secret
data:
    .dockerconfigjson: {{ template "imagePullSecret" . }} 
type: kubernetes.io/dockerconfigjson