apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-tag
spec:
  params:
    - name: git_ref
      value: $(body.ref)
    - name: git_ref_type
      value: $(body.ref_type)
    - name: repo_name
      value: $(body.repo_name)
    - name: repo_url
      value: $(body.repo_url)
    - name: default_branch
      value: $(body.default_branch)
